config/routes.rb
Rails.application.routes.draw do


  resources :credit_cards
  get '/wallet' => 'credit_cards#index'
  root :to => redirect('/wallet')

end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_credit_card, only: [:destroy]

  # GET /credit_cards
  # GET /credit_cards.json
  def index
    @credit_cards = CreditCard.all
  end

  # GET /credit_cards/new
  def new
    @credit_card = CreditCard.new
  end

  # POST /credit_cards
  # POST /credit_cards.json
  def create
    @credit_card = CreditCard.new(credit_card_params)
    if @credit_card.save
      redirect_to '/wallet', notice: 'Credit card was successfully created.' 
    else
      render :new 
    end
  end

  
  def destroy
    @credit_card.destroy
    redirect_to '/wallet', notice: 'Credit card was successfully destroyed.' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card
      @credit_card = CreditCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_card_params
      params.require(:credit_card).permit(:number, :cvv, :expiration_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/index.html.erb
<div class="container main-container">
<div class="row">
<div class="col-sm-6 col-sm-offset-3">
<% if notice %>
<div class="row">
<div class="alert alert-success btn-block text-center">
  <%= notice %>
</div>
</div>
<% end %>
<h1 class="text-center">Your wallet</h1>
<div class="container" >
    <% @credit_cards.each do |credit_card| %>
    <div class="row text-right" style="padding-top: 6%;padding-bottom: 6%">
    <div class="col-sm-6">

      <%= link_to '<i class="fa fa-times"></i>'.html_safe, credit_card, method: :delete, data: { confirm: 'Are you sure you want to delete this card from your wallet?' } %>


      <hr>
      <div class="row" style="font-size: 25px">
      <div class="col-sm-9 text-left">
      <i class="fa fa-credit-card "></i> ************<%= credit_card.number.last(5) %> 
      </div>
      <div class="col-sm-3 text-right text-muted"><%= credit_card.expiration_date.strftime("%m/%Y")  %> </div>
      </div>
      </div>
    </div>
    <% end %>
</div>
<br>
<br>
<br>
<div class="row text-center">
<div class="col-sm-12">
<%= link_to 'ADD NEW CARD', new_credit_card_path, {class: 'button btn-block '} %>
</div>
</div>
</div>
</div>
</div>

app/views/credit_cards/new.html.erb
<div class="container main-container">
<div class="row">
<div class="col-sm-6 col-sm-offset-3">
<h1 class="text-center">New Credit Card</h1>
<br>
<div class="row">
<%= form_for(@credit_card) do |f| %>
  <% if @credit_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
      <% @credit_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <form>
  <div class="form-group">
    <%= f.label :number %><br>
    <%= f.text_field :number, {class: 'violet-input btn-block', required: true, data: {mask: '9999 9999 9999 9999'}} %>
  </div>
  <div class="form-group">
    <%= f.label :cvv %><br>
    <%= f.text_field :cvv, {class: 'violet-input btn-block', required: true, data: {mask: '999'}} %>
  </div>
  <div class="form-check">
    <%= f.label :expiration_date %><br>
    <%= f.date_select :expiration_date, {discard_day: true, class: 'violet-input btn-block'} %>
  </div>
  <hr>
  <div class="row">
  <button type="submit" class="button small btn-block">SUBMIT</button>
  <a href="/wallet" class="button small btn-block">RETURN</a>
  </div>
</form>
 
<% end %>
</div>
</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WalletMejuriTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Enriqueta" rel="stylesheet"> 
  
  <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>